# Brews
brew "asdf"
brew "awscli"
brew "btop"
brew "chezmoi"
brew "colima"
brew "docker"
brew "eza"
brew "fd"
brew "gh"
brew "jq"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "uv"
brew "watchman"
brew "worktrunk"
brew "yq"

# Casks
cask "font-hack-nerd-font"
cask "iterm2"
cask "visual-studio-code"

